### PR TITLE
ci: Run Integration Tests as part of PR checks

### PR DESCRIPTION
**Pull request by rm3l**
## Description

As the PR title suggests, this allows us to enforce that integration tests are run as part of the PR validation checks.
Currently, we are only running unit tests with `make test`. In the past, `make test` used to cover a lot more via [EnvTest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest), but this part has been moved to a `make integration-test` target since https://github.com/janus-idp/operator/pull/272).

As I almost always happen to run this target (along with the E2E tests) when reviewing PRs, I think we should enforce those integration tests as part of the automatic PR checks. Unlike the E2E tests, they don't take that long to run and do not require a cluster to run.

## Which issue(s) does this PR fix or relate to

&mdash;

## PR acceptance criteria

- [ ] Tests
- [ ] Documentation
- [ ] If the bundle manifests have been updated, make sure to review the [`rhdh-operator.csv.yaml`](../.rhdh/bundle/manifests/rhdh-operator.csv.yaml) file accordingly

## How to test changes / Special notes to the reviewer
Job passing: https://github.com/janus-idp/operator/actions/runs/9177666830/job/25235797784?pr=365

### CODE REVIEW

**Review by gazarenkov — CHANGES_REQUESTED** [review]
I think "make test" already included integration_tests, no?

Like:

```
ok      redhat-developer/red-hat-developer-hub-operator/controllers     0.529s  coverage: 22.8% of statements
ok      redhat-developer/red-hat-developer-hub-operator/integration_tests       7.824s  coverage: 42.2% of statements
ok      redhat-developer/red-hat-developer-hub-operator/pkg/model       1.240s  coverage: 84.6% of statements

```

**Comment by rm3l** [comment]
> I think "make test" already included integration_tests, no?
> 
> Like:
> 
> ```
> ok      redhat-developer/red-hat-developer-hub-operator/controllers     0.529s  coverage: 22.8% of statements
> ok      redhat-developer/red-hat-developer-hub-operator/integration_tests       7.824s  coverage: 42.2% of statements
> ok      redhat-developer/red-hat-developer-hub-operator/pkg/model       1.240s  coverage: 84.6% of statements
> ```

🤔 Interesting.. I thought so initially, but they didn't seem to be included on my machine:

```
$ make test                                                            
test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.3
/home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/goimports || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install golang.org/x/tools/cmd/goimports@v0.15.0
find . -not -path '*/\.*' -name '*.go' -exec /home/asoro/work/projects/backstage/janus-idp/operator/bin/goimports -w {} \;
go vet ./...
test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/setup-envtest || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@c7e1dc9b5302d649d5531e19168dd7ea0013736d
mkdir -p /home/asoro/work/projects/backstage/janus-idp/operator/bin/default-config && cp config/manager/default-config/* /home/asoro/work/projects/backstage/janus-idp/operator/bin/default-config
LOCALBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin KUBEBUILDER_ASSETS="/home/asoro/work/projects/backstage/janus-idp/operator/bin/k8s/1.25.0-linux-amd64" go test redhat-developer/red-hat-developer-hub-operator redhat-developer/red-hat-developer-hub-operator/api/v1alpha1 redhat-developer/red-hat-developer-hub-operator/controllers redhat-developer/red-hat-developer-hub-operator/integration_tests redhat-developer/red-hat-developer-hub-operator/pkg/model redhat-developer/red-hat-developer-hub-operator/pkg/utils -coverprofile cover.out
?       redhat-developer/red-hat-developer-hub-operator [no test files]
?       redhat-developer/red-hat-developer-hub-operator/api/v1alpha1    [no test files]
ok      redhat-developer/red-hat-developer-hub-operator/controllers     0.013s  coverage: 22.8% of statements
?       redhat-developer/red-hat-developer-hub-operator/pkg/utils       [no test files]
ok      redhat-developer/red-hat-developer-hub-operator/pkg/model       0.057s  coverage: 85.4% of statements
```

**Comment by rm3l** [comment]
> > I think "make test" already included integration_tests, no?
> > Like:
> > ```
> > ok      redhat-developer/red-hat-developer-hub-operator/controllers     0.529s  coverage: 22.8% of statements
> > ok      redhat-developer/red-hat-developer-hub-operator/integration_tests       7.824s  coverage: 42.2% of statements
> > ok      redhat-developer/red-hat-developer-hub-operator/pkg/model       1.240s  coverage: 84.6% of statements
> > ```
> 
> 🤔 Interesting.. I thought so initially, but they didn't seem to be included on my machine:
> 
> ```
> $ make test                                                            
> test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.3
> /home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
> /home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
> test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/goimports || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install golang.org/x/tools/cmd/goimports@v0.15.0
> find . -not -path '*/\.*' -name '*.go' -exec /home/asoro/work/projects/backstage/janus-idp/operator/bin/goimports -w {} \;
> go vet ./...
> test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/setup-envtest || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@c7e1dc9b5302d649d5531e19168dd7ea0013736d
> mkdir -p /home/asoro/work/projects/backstage/janus-idp/operator/bin/default-config && cp config/manager/default-config/* /home/asoro/work/projects/backstage/janus-idp/operator/bin/default-config
> LOCALBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin KUBEBUILDER_ASSETS="/home/asoro/work/projects/backstage/janus-idp/operator/bin/k8s/1.25.0-linux-amd64" go test redhat-developer/red-hat-developer-hub-operator redhat-developer/red-hat-developer-hub-operator/api/v1alpha1 redhat-developer/red-hat-developer-hub-operator/controllers redhat-developer/red-hat-developer-hub-operator/integration_tests redhat-developer/red-hat-developer-hub-operator/pkg/model redhat-developer/red-hat-developer-hub-operator/pkg/utils -coverprofile cover.out
> ?       redhat-developer/red-hat-developer-hub-operator [no test files]
> ?       redhat-developer/red-hat-developer-hub-operator/api/v1alpha1    [no test files]
> ok      redhat-developer/red-hat-developer-hub-operator/controllers     0.013s  coverage: 22.8% of statements
> ?       redhat-developer/red-hat-developer-hub-operator/pkg/utils       [no test files]
> ok      redhat-developer/red-hat-developer-hub-operator/pkg/model       0.057s  coverage: 85.4% of statements
> ```

They appear to be included in the CI, but I still am not sure why they are not on my machine. Closing this PR since they run in CI - will look into the local issue later.

/close

**Pull request closed without merging**
