### PR TITLE
add resources.requests to default config

### PR DESCRIPTION
**Pull request by gazarenkov**
## Description

add resources.requests to default config

## Which issue(s) does this PR fix or relate to

https://issues.redhat.com/browse/RHIDP-2159

## PR acceptance criteria

- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Review by nickboldt — CHANGES_REQUESTED** [review]
Please apply these changes in the [.rhdh folder](https://github.com/janus-idp/operator/tree/1.1.x/.rhdh) too, and comment on this PR or the JIRA, to let me know if this needs to be fixed in main branch as well.

**Comment by gazarenkov** [comment]
> Please apply these changes in the [.rhdh folder](https://github.com/janus-idp/operator/tree/1.1.x/.rhdh) too, and comment on this PR or the JIRA, to let me know if this needs to be fixed in main branch as well.

Please let me know what exactly to change. Unless I missed something there are no changes in .rhdh's CSV? it should come with:
`
              volumes:
              - configMap:
                  name: backstage-default-config
                name: default-config
`
No needs to fix in main, it should be already there.

**Comment by nickboldt** [comment]
oops, sorry -- I saw a change to configmap and a timestamp in the CSV and misread that as real changes to the CSV. Not sure why you updated the timestamp if nothing was changed in the CSV, but it's cool, I can merge this.

**Review by nickboldt — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
