### PR TITLE
feat: RHIDP-488 new downstream rhdh-operator...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

feat: [RHIDP-488](https://issues.redhat.com/browse/RHIDP-488) new downstream rhdh-operator CSV

Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/RHIDP-488

### Questions:

- [x] new csv has [backstages.janus-idp.io](http://backstages.janus-idp.io/) where old one had [backstages.charts.janus-idp.io](http://backstages.charts.janus-idp.io/) ... I assume that's expected because this NOT a helmchart hybrid operator

- [x] What do you do with [gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0](http://gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0) and is there a downstream equivalent from https://catalog.redhat.com/software/containers/search?q=rbac we can use instead? maybe https://catalog.redhat.com/software/containers/openshift4/ose-kube-rbac-proxy/5cdb2634dd19c778293b4d98 works for your needs?

- [x] the old operator deployed a pod with [registry.redhat.io/rhel9/postgresql-15:latest](http://registry.redhat.io/rhel9/postgresql-15:latest) in it... I don't see that in your CSV. Here's what was in the old hybrid one:
```
                    env:
                      - name: OPERATOR_NAME
                        value: rhdh-operator
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: RELATED_IMAGE_hub
                        value: registry-proxy.engineering.redhat.com/rh-osbs/rhdh-rhdh-hub-rhel9:1.0
                      - name: RELATED_IMAGE_postgresql
                        value: registry.redhat.io/rhel9/postgresql-15:latest
```
Are you defining this pod deployment some other way?

### CODE REVIEW

**Comment by jianrongzhang89** [comment]
@nickboldt about the psql image: it is defined here:
https://github.com/janus-idp/operator/blob/main/config/manager/default-config/db-statefulset.yaml#L32
It is not included in the csv directly, rather, a configmap  backstage-default-config is generated with all files under the same folder and then the config map is mounted in the operator container.

**Comment by jianrongzhang89** [comment]
@nickboldt About this one: "new csv has [backstages.janus-idp.io](http://backstages.janus-idp.io/) where old one had [backstages.charts.janus-idp.io](http://backstages.charts.janus-idp.io/) ... I assume that's expected because this NOT a helmchart hybrid operator":  yes this is expected.

**Comment by nickboldt** [comment]
I don't know what embedding container refs in a place outside the CSV will do on airgapped clusters.

My gut feeling is that it won't work for two reasons:
* fedora container is not signed/certified like the RHEL one in RHEC, so this is bad/unsupported -- we should use the RHEL8 postgres container here.

* container won't be easily copied into the internal OCP podman registry, so manual steps will be needed by an administrator to enable use of the postgres pod, and the error a user will see will be the usual `crash loop back off` error, which won't immediately point to the cause being that inside the airgapped cluster, the image is not available thru the firewall/proxy

So... if possible... moving ALL container refs into the CSV as env vars, then exposing them where needed would be better for airgapped scenarios. I can point you at the code that does this in Dev Spaces, where we solved this years ago.

**Review by rm3l — COMMENTED** [review]
I tried to run `make bundle` but validation did not pass. I guess because of the 2 CSVs..
Just curious, what would then be the "best" way to perform bundle validation now?

```
$ make bundle                    
test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen || GOBIN=/home/asoro/work/projects/backstage/janus-idp/operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.3
/home/asoro/work/projects/backstage/janus-idp/operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
test -s /home/asoro/work/projects/backstage/janus-idp/operator/bin/kustomize || { curl -Ss "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.7 /home/asoro/work/projects/backstage/janus-idp/operator/bin; }
operator-sdk generate kustomize manifests -q
cd config/manager && /home/asoro/work/projects/backstage/janus-idp/operator/bin/kustomize edit set image controller=quay.io/asoro/backstage-operator
/home/asoro/work/projects/backstage/janus-idp/operator/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Creating bundle/metadata/annotations.yaml    
INFO[0000] Bundle metadata generated successfully       
operator-sdk bundle validate ./bundle
FATA[0000] [error loading objs in directory: invalid bundle: contains multiple CSVs, no bundle csv found, unable to load bundle from directory bundle/manifests] 
make: *** [Makefile:253: bundle] Error 1
```

**Comment by rm3l** [comment]
> I don't know what embedding container refs in a place outside the CSV will do on airgapped clusters.
> 
> My gut feeling is that it won't work for two reasons:
> 
> * fedora container is not signed/certified like the RHEL one in RHEC, so this is bad/unsupported -- we should use the RHEL8 postgres container here.
> * container won't be easily copied into the internal OCP podman registry, so manual steps will be needed by an administrator to enable use of the postgres pod, and the error a user will see will be the usual `crash loop back off` error, which won't immediately point to the cause being that inside the airgapped cluster, the image is not available thru the firewall/proxy
> 
> So... if possible... moving ALL container refs into the CSV as env vars, then exposing them where needed would be better for airgapped scenarios. I can point you at the code that does this in Dev Spaces, where we solved this years ago.

Yes @nickboldt, that would be helpful - thanks!
btw, I created a dedicated issue to support the airgap scenario: https://github.com/janus-idp/operator/issues/80

**Pull request merged**
