### PR TITLE
[1.1.x] increase controller memory limit

### PR DESCRIPTION
**Pull request by gazarenkov**
## Description
Increase the memory limit for controller to avoid OOMKill on loaded cluster.

## Which issue(s) does this PR fix or relate to

https://issues.redhat.com/browse/RHIDP-2036

## PR acceptance criteria

- [x] Tests

### CODE REVIEW

**Comment by coreydaley** [comment]
@gazarenkov Is this a temporary change until the reconciliation is fixed or are you thinking that this is a long term fix?

**Comment by gazarenkov** [comment]
> @gazarenkov Is this a temporary change until the reconciliation is fixed or are you thinking that this is a long term fix?

Well, realistically speaking, I think that's pretty much all we can do for 1.1.x

**Comment by kadel** [comment]
/lgtm
/approve

As a temporary solution, this is good. However, we should not close https://issues.redhat.com/browse/RHIDP-2036 with this as a solution. This is more like temporary workaround.

**Comment by gazarenkov** [comment]
> /lgtm /approve
> 
> As a temporary solution, this is good. However, we should not close https://issues.redhat.com/browse/RHIDP-2036 with this as a solution. This is more like temporary workaround.

@kadel 
Thanks for approving.
Note, this is the issue for 1.1.x only

**Comment by nickboldt** [comment]
PRs for 1.1.x and main to update the RHDH csv (you forgot to update that when updating the upstream one):

https://github.com/janus-idp/operator/pull/315 (1.1.x)
https://github.com/janus-idp/operator/pull/316 (main)

I'm now realizing that maybe you didn't want this fix in main branch... please confirm - it's easy enough for anyone to revert my change to the RHDH CSV in #316.

**Pull request merged**
