### PR TITLE
chore: tweak the names of jobs run on PR...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: tweak the names of jobs run on PR checks for consistency

Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
Fix the inconsistent names for the stages in PR checks:

image

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by rm3l — APPROVED** [review]
@nickboldt LGTM, but after this PR is merged, I think we'll need to update the Prow config accordingly, for the merge automation bot to work properly: https://github.com/openshift/release/blob/master/core-services/prow/02_config/janus-idp/operator/_prowconfig.yaml#L9-L12

**Comment by nickboldt** [comment]
moving back to draft to avoid automerge before the change to prow is ready to merge

**Review by rm3l — APPROVED** [review]
/hold

re https://github.com/janus-idp/operator/pull/146#issuecomment-1894140489

> moving back to draft to avoid automerge before the change to prow is ready to merge

Is the change to Prow ready?

**Comment by nickboldt** [comment]
replaced by  #158

**Pull request closed without merging**
